### ISSUE TITLE
Should bioconductor_full be built on terra-jupyter-r instead?

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_full#19]
I'm wondering whether these images should instead be built instead on [terra-jupyter-r](https://github.com/DataBiosphere/terra-docker/tree/master/terra-jupyter-r), or one of its parent images terra-jupyter-base, or `marketplace.gcr.io/google/ubuntu1804` if you don't want the Jupyter or Terra bits?

Here are the reasons I'm wondering:

1. It would be nice to have Jupyter in addition or as an alternative to RStudio
2. It would be nice to use the same image on my desktop as on app.terra.bio
3. Perhaps system dependencies should be installed on a more bare-bones container *before* layering on the version of R/Bioconductor and the user interfaces RStudio and/or Jupyter. This would allow more lightweight Docker pulls of the software that Bioconductor updates regularly. This may not be a big advantage though since the images are only updated every 6 months.
4. The rocker images do things that may be unnecessary for Bioconductor's purposes, like adding the "rstudio" user. It also adds the s6 layer and launches rstudio-server on `/init`, which I don't totally understand but may limit its uses other than running rstudio-server.

**Comment by mtmorgan** [comment]
My understanding is that the terra images have infrastructure that means they actually can't be run stand-alone.

Also, I think the idea is that the bioc_full images provide R & Bioc rather than xxx where for Jupyter that would include a python installation.

I don't think the /init stuff is limiting to other functionality (it isn't run if you specify a command, e.g., `docker run ... bioc_full:devel R`). I think it's 'necessary' to start RStudioServer, and one would just have to invent another wheel...

The rstudio user can be more aggressively removed without too much cost if that's desirable.

Maybe though I'm just not familiar enough with notebooks, compared to RStudio, to see the compelling case.

**Comment by lwaldron** [comment]
I had trouble trying to start rstudio-server using `rstudio-server start` instead of using the /init command, but that may just be my own limitations.  FYI my use case for the notebooks has teaching to beginners - my experience with handing RStudio to beginners is that the class becomes at least as much about teaching RStudio than R, whereas most people seem to just "get" the notebooks without much teaching about them.

I'll try extending bioconductor_full with jupyter, and as long as I'm still able to start another server for jupyter, then there's no problem. On the other hand, there are some Cloud installations of jupyter/r that seem to work well enough that I don't even need it running on the desktop...
